### ISSUE TITLE
sqlmap need update version for current

### ISSUE THREAD

**Issue by rizitis** [Ponce/slackbuilds#234]
Hello ponce.

sqlmap-1.4.9 build fine in current but not run because of python 3.11
provide error: 
```
> sqlmap
Traceback (most recent call last):
  File "/opt/sqlmap-1.4.9/./sqlmap.py", line 42, in <module>
    from lib.core.data import logger
  File "/opt/sqlmap-1.4.9/lib/core/data.py", line 8, in <module>
    from lib.core.datatype import AttribDict
  File "/opt/sqlmap-1.4.9/lib/core/datatype.py", line 158, in <module>
    class OrderedSet(collections.MutableSet):
                     ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'MutableSet'
```
New version `https://github.com/sqlmapproject/sqlmap/archive/1.8.7/sqlmap-1.8.7.tar.gz`
build and run fine:
```
sqlmap
        ___
       __H__
 ___ ___[.]_____ ___ ___  {1.8.7#stable}
|_ -| . ["]     | .'| . |
|___|_  ["]_|_|_|__,|  _|
      |_|V...       |_|   https://sqlmap.org

Usage: python sqlmap.py [options]

sqlmap.py: error: missing a mandatory option (-d, -u, -l, -m, -r, -g, -c, --wizard, --shell, --update, --purge, --list-tampers or --dependencies). Use -h for basic and -hh for advanced help
```

thanks!

**Comment by Ponce** [comment]
thanks for the heads-up, pushed in a dedicated branch!
